# Generated by Django 6.0.2 on 2026-02-24 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in-use', 'In Use'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('driver', models.CharField(blank=True, max_length=100)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('fuel_level', models.IntegerField(default=100)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('current_load', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stops', models.IntegerField(default=0)),
                ('distance', models.CharField(max_length=50)),
                ('estimated_time', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('efficiency', models.IntegerField(default=0)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicle')),
            ],
        ),
    ]
