# Generated by Django 6.0.2 on 2026-05-12 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_type', models.CharField(choices=[('LMV', 'Light Motor Vehicle'), ('HMV', 'Heavy Motor Vehicle'), ('TRANSPORT', 'Transport Vehicle')], default='HMV', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('experience_years', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('customer', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('loading', 'Loading'), ('in-transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed')], default='preparing', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicle')),
            ],
        ),
    ]
