# Generated by Django 6.0.2 on 2026-10-06 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_company_id_alter_companysubscription_id_and_more'),
        ('inventory', '0022_batch_parent_batch_qa_status'),
        ('sales', '0014_invoiceline_sales_order_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('picking', 'Picking'), ('picked', 'Picked'), ('packed', 'Packed'), ('staged', 'Staged'), ('prepared', 'Shipment Prepared'), ('verified', 'Dispatch Verified'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='picking', max_length=20)),
                ('shipment_mode', models.CharField(blank=True, choices=[('road', 'Road'), ('sea', 'Sea'), ('air', 'Air'), ('rail', 'Rail'), ('courier', 'Courier'), ('customer_pickup', 'Customer Pickup')], default='', max_length=20)),
                ('carrier', models.CharField(blank=True, default='', max_length=200)),
                ('shipment_reference', models.CharField(blank=True, default='', help_text='AWB / B/L / LR / tracking no.', max_length=100)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=50)),
                ('driver_name', models.CharField(blank=True, default='', max_length=100)),
                ('transport_details', models.TextField(blank=True, default='')),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('packages', models.PositiveIntegerField(default=0)),
                ('gross_weight', models.CharField(blank=True, default='', max_length=50)),
                ('ship_to_name', models.CharField(blank=True, default='', max_length=200)),
                ('ship_to_address', models.TextField(blank=True, default='')),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, default='', max_length=150)),
                ('delivery_notes', models.TextField(blank=True, default='')),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('staged_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='sales.invoice')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='sales.salesorder')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='sales.shipment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DispatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.FloatField()),
                ('quantity', models.FloatField(default=0, help_text='Picked quantity')),
                ('packed', models.BooleanField(default=False)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fulfillment.dispatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.item')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_lines', to='sales.salesorderitem')),
            ],
        ),
        migrations.CreateModel(
            name='FGAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('dispatched_quantity', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('active', 'Allocated'), ('dispatched', 'Dispatched'), ('released', 'Released')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_allocations', to='sales.salesorder')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_allocations', to='sales.salesorderitem')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
