# Generated by Django 6.0.2 on 2026-02-28 15:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('inventory', 'Inventory'), ('quality', 'Quality Control'), ('production', 'Production'), ('maintenance', 'Maintenance'), ('procurement', 'Procurement'), ('logistics', 'Logistics'), ('hr', 'Human Resources'), ('sales', 'Sales'), ('admin', 'Administration')], max_length=50)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('period_label', models.CharField(help_text="e.g. 'Jan 2026', 'Q1 2026'", max_length=50)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('auto_approve_limit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Expense requests below this amount are auto-approved if within budget.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('department', 'period_label')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('raw_material', 'Raw Materials'), ('equipment', 'Equipment'), ('maintenance', 'Maintenance & Repairs'), ('utilities', 'Utilities'), ('packaging', 'Packaging'), ('labor', 'Labor / Contractor'), ('transport', 'Transport / Logistics'), ('software', 'Software / IT'), ('safety', 'Safety & Compliance'), ('training', 'Training'), ('miscellaneous', 'Miscellaneous')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('auto_approved', 'Auto Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes / rejection reason')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_requests', to='finance.departmentbudget')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=50, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_payroll', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='COGS')),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('cost_type', models.CharField(choices=[('fixed', 'Fixed Cost'), ('variable', 'Variable Cost'), ('one_time', 'One-Time Cost')], max_length=20)),
                ('department', models.CharField(choices=[('inventory', 'Inventory'), ('quality', 'Quality Control'), ('production', 'Production'), ('maintenance', 'Maintenance'), ('procurement', 'Procurement'), ('logistics', 'Logistics'), ('hr', 'Human Resources'), ('sales', 'Sales'), ('admin', 'Administration')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('expense_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_cost', to='finance.expenserequest')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_costs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(help_text="e.g. 'January 2026'", max_length=50)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('paid', 'Paid'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'period_label')},
            },
        ),
    ]
