# Generated by Django 5.2.15 on 2026-07-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_id'),
        ('finance', '0002_departmentbudget_company_expenserequest_company_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentbudget',
            unique_together={('company', 'department', 'period_label')},
        ),
    ]
