# Generated by Django 6.0.2 on 2026-02-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionline_productionorder_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='capacity',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='productionline',
            name='location',
            field=models.CharField(default='Main Facility', max_length=200),
        ),
    ]
