# Generated by Django 6.0.2 on 2026-02-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20260225_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('maintenance', 'Maintenance')], default='running', max_length=20),
        ),
    ]
