# Generated by Django 6.0.2 on 2026-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_productionline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='materials_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
