# Generated by Django 5.2.15 on 2026-07-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_productionline_company_alter_productionline_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='batch_size',
            field=models.FloatField(default=1, help_text='Finished units produced per production batch'),
        ),
    ]
