# Generated by Django 6.0.2 on 2026-10-06 13:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_company_id_alter_companysubscription_id_and_more'),
        ('inventory', '0020_alter_batch_id_alter_bom_id_alter_bomline_id_and_more'),
        ('production', '0010_productionorder_sales_order_alter_productionline_id_and_more'),
        ('sales', '0012_alter_customer_address_alter_customer_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('order_quantity', models.FloatField()),
                ('planned_quantity', models.FloatField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('converted', 'Converted to Production'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_plans', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_plans', to='sales.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='inventory.item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='sales.salesorder')),
                ('sales_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_plans', to='sales.salesorderitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_plan',
            field=models.ForeignKey(blank=True, help_text='The Production Plan Order from which this batch was raised.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='production.productionplan'),
        ),
    ]
