# Generated by Django 6.0.2 on 2026-10-01 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_productionorder_sales_order_alter_productionline_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='default_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.productionline'),
        ),
    ]
