# Generated by Django 6.0.2 on 2026-10-06 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_company_id_alter_companysubscription_id_and_more'),
        ('inventory', '0022_batch_parent_batch_qa_status'),
        ('maintenance', '0012_alter_equipment_id_alter_maintenancetask_id'),
        ('production', '0012_productionmaterialrequirement'),
        ('workforce', '0004_alter_attendancerecord_id_alter_department_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='planned_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='planned_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='produced_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_plan_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='qa_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'QA Pending'), ('partial', 'QA Partially Passed'), ('passed', 'QA Passed'), ('failed', 'QA Failed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='rework_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_orders', to='production.productionorder'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='rework_source_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_orders', to='inventory.batch'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('material_pending', 'Material Pending'), ('scheduled', 'Ready for Production'), ('running', 'In Production'), ('partially_completed', 'Partially Completed'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='ManufacturingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforce_operation_sequence', models.BooleanField(default=True)),
                ('incoming_qc_required', models.BooleanField(default=False)),
                ('auto_invoice_on_dispatch', models.BooleanField(default=True)),
                ('overhead_method', models.CharField(choices=[('none', 'No overhead'), ('per_unit', 'Fixed amount per good unit'), ('percent_of_material', 'Percent of raw material cost'), ('per_machine_hour', 'Rate per machine hour'), ('per_labour_hour', 'Rate per labour hour')], default='none', max_length=30)),
                ('overhead_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('default_hours_per_shift', models.FloatField(default=8)),
                ('default_shifts_per_day', models.FloatField(default=1)),
                ('default_working_days_per_week', models.FloatField(default=6)),
                ('overload_threshold_percent', models.FloatField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_settings', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.batch')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='production.productionorder')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('machine', 'Machine'), ('manpower', 'Manpower')], max_length=20)),
                ('category', models.CharField(blank=True, default='', help_text='Machine type or labour role', max_length=100)),
                ('skill', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('shift_name', models.CharField(blank=True, default='', max_length=100)),
                ('hours_per_shift', models.FloatField(blank=True, null=True)),
                ('shifts_per_day', models.FloatField(blank=True, null=True)),
                ('working_days_per_week', models.FloatField(blank=True, null=True)),
                ('run_rate_per_hour', models.FloatField(default=0)),
                ('units', models.PositiveIntegerField(default=1)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maintenance', 'Maintenance'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workforce.employee')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='maintenance.equipment')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='production.productionline')),
            ],
            options={
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability', to='production.resource')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='RoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('setup_minutes', models.FloatField(default=0)),
                ('run_minutes_per_unit', models.FloatField(default=0)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('allow_out_of_sequence', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.resource')),
                ('manpower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.resource')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_steps', to='production.recipe')),
            ],
            options={
                'ordering': ['recipe', 'sequence'],
                'unique_together': {('recipe', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='ProductionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('planned_quantity', models.FloatField(default=0)),
                ('started_quantity', models.FloatField(default=0)),
                ('completed_quantity', models.FloatField(default=0)),
                ('rejected_quantity', models.FloatField(default=0)),
                ('rework_quantity', models.FloatField(default=0)),
                ('scrap_quantity', models.FloatField(default=0)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, default='', max_length=150)),
                ('setup_minutes', models.FloatField(default=0)),
                ('run_minutes_per_unit', models.FloatField(default=0)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('actual_minutes', models.FloatField(blank=True, null=True)),
                ('allow_out_of_sequence', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('rework_required', 'Rework Required')], default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.productionorder')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_operations', to='production.resource')),
                ('manpower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_operations', to='production.resource')),
                ('routing_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.routingstep')),
            ],
            options={
                'ordering': ['production_order', 'sequence'],
                'unique_together': {('production_order', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='ScrapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('operation', 'Shop floor operation'), ('qa', 'QA rejection'), ('manual', 'Manual entry')], default='operation', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cost_impact', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.batch')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_records', to='production.productionoperation')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_records', to='production.productionorder')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.resource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
