# Generated by Django 6.0.2 on 2026-10-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_backfill_track_b_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraprecord',
            name='gl_treatment',
            field=models.CharField(choices=[('covered', "Included in the production order's manufacturing entry"), ('finished_goods', 'Write off from finished goods inventory'), ('raw_material', 'Write off from raw material inventory')], default='covered', max_length=20),
        ),
    ]
