# Generated by Django 6.0.2 on 2026-10-07 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_scraprecord_gl_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingsettings',
            name='shift_start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
