# Generated by Django 6.0.2 on 2026-10-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_productionplan_productionorder_production_plan'),
        ('production', '0016_manufacturingsettings_shift_start_time'),
    ]

    operations = [
    ]
