# Generated by Django 6.0.2 on 2026-10-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_merge_20261007_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingsettings',
            name='allow_partial_production_and_dispatch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manufacturingsettings',
            name='business_model',
            field=models.CharField(choices=[('mto', 'Make to Order'), ('mts', 'Make to Stock'), ('hybrid', 'Make to Order and Make to Stock')], default='mto', max_length=10),
        ),
        migrations.AddField(
            model_name='manufacturingsettings',
            name='customer_order_approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manufacturingsettings',
            name='include_open_purchase_orders_in_mrp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manufacturingsettings',
            name='production_plan_approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manufacturingsettings',
            name='protect_safety_stock_in_mrp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manufacturingsettings',
            name='require_materials_available_for_conversion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('planned', 'Planned'), ('partially_converted', 'Partially Converted'), ('converted', 'Converted to Production'), ('cancelled', 'Cancelled')], default='draft', max_length=25),
        ),
    ]
