# Generated by Django 6.0.2 on 2026-10-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_manufacturingsettings_allow_partial_production_and_dispatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingsettings',
            name='business_rules_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manufacturingsettings',
            name='business_rules_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
