# Generated by Django 6.0.2 on 2026-02-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_approve_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Procurement orders below this amount will be auto-approved for this user.', max_digits=12),
        ),
    ]
