# Generated by Django 6.0.2 on 2026-02-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_finished_good',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('raw_material', 'Raw Material'), ('finished_good', 'Finished Good')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(default='unit', max_length=50),
        ),
    ]
