# Generated by Django 6.0.2 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_inventoryrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("procuring", "Procuring"),
                    ("supplied", "Supplied"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
