# Generated by Django 5.2.15 on 2026-07-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_company_warehouse_company_alter_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
