# Generated by Django 5.2.15 on 2026-07-13 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_company_id_alter_companysubscription_id_and_more'),
        ('inventory', '0010_alter_batch_id_alter_inventoryrequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bom_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='classification_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='erp_classification',
            field=models.CharField(blank=True, choices=[('raw_material', 'Raw Material'), ('finished_good', 'Finished Good'), ('out_of_scope', 'Out of Scope')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_good', models.OneToOneField(limit_choices_to={'category': 'finished_good'}, on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='QuickBooksOnboarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('classification', 'Awaiting Item Classification'), ('bom_setup', 'Awaiting BOM Setup'), ('completed', 'Completed')], default='classification', max_length=20)),
                ('disclaimer_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qb_onboarding', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Quantity of raw material per unit of finished good')),
                ('unit', models.CharField(default='unit', max_length=50)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.bom')),
                ('raw_material', models.ForeignKey(limit_choices_to={'category': 'raw_material'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
            options={
                'unique_together': {('bom', 'raw_material')},
            },
        ),
    ]
