# Generated by Django 5.2.15 on 2026-07-29 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_company_id_alter_companysubscription_id_and_more'),
        ('inventory', '0014_alter_procurementquickbooksconfig_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code, e.g. g, oz, lb, case, each', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('dimension', models.CharField(choices=[('mass', 'Mass'), ('count', 'Count'), ('volume', 'Volume')], max_length=20)),
                ('to_base_factor', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('is_base', models.BooleanField(default=False, help_text='The reference unit for its dimension')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
            ],
            options={
                'ordering': ['dimension', 'code'],
            },
        ),
        migrations.AddField(
            model_name='bomline',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.unitofmeasure'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_uom_code_per_company'),
        ),
    ]
