# Generated by Django 5.2.15 on 2026-07-29 15:59

from django.db import migrations


def seed_units(apps, schema_editor):
    from inventory.uom import STANDARD_UNITS

    UnitOfMeasure = apps.get_model("inventory", "UnitOfMeasure")
    for code, name, dimension, to_base, is_base in STANDARD_UNITS:
        UnitOfMeasure.objects.get_or_create(
            company=None,
            code=code,
            defaults={
                "name": name,
                "dimension": dimension,
                "to_base_factor": to_base,
                "is_base": is_base,
            },
        )


def unseed_units(apps, schema_editor):
    from inventory.uom import STANDARD_UNITS

    UnitOfMeasure = apps.get_model("inventory", "UnitOfMeasure")
    UnitOfMeasure.objects.filter(
        company=None, code__in=[u[0] for u in STANDARD_UNITS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_unitofmeasure_bomline_unit_of_measure_item_base_unit_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_units, unseed_units),
    ]
