# Generated by Django 5.2.15 on 2026-07-29 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_company_id_alter_companysubscription_id_and_more'),
        ('inventory', '0016_seed_standard_units'),
        ('procurement', '0007_alter_bill_id_alter_billline_id_and_more'),
        ('production', '0008_productionline_company_alter_productionline_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='batch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='procurement.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='batch',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='production.productionorder'),
        ),
        migrations.AddField(
            model_name='batch',
            name='remaining_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='source',
            field=models.CharField(choices=[('received', 'Received from vendor'), ('produced', 'Produced in-house'), ('legacy', 'Legacy / manual')], default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='batch',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='LotConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed_in', to='inventory.batch')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_consumptions', to='production.productionorder')),
            ],
        ),
    ]
