# Generated by Django 6.0.2 on 2026-10-06 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_batch_id_alter_bom_id_alter_bomline_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='bom',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='bom',
            name='finished_good',
            field=models.OneToOneField(limit_choices_to={'category__in': ['finished_good', 'intermediate']}, on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='quantity',
            field=models.FloatField(help_text='Quantity of component per unit of parent good'),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='raw_material',
            field=models.ForeignKey(limit_choices_to={'category__in': ['raw_material', 'intermediate']}, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('raw_material', 'Raw Material'), ('intermediate', 'Intermediate (semi-finished)'), ('finished_good', 'Finished Good')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='erp_classification',
            field=models.CharField(blank=True, choices=[('raw_material', 'Raw Material'), ('intermediate', 'Intermediate (semi-finished)'), ('finished_good', 'Finished Good'), ('out_of_scope', 'Out of Scope')], max_length=20, null=True),
        ),
    ]
