# Generated by Django 6.0.2 on 2026-10-06 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_intermediate_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_lots', to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='qa_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'QA Pending'), ('approved', 'QA Approved'), ('rejected', 'QA Rejected'), ('quarantine', 'Quarantine'), ('rework', 'Rework'), ('scrapped', 'Scrapped')], db_index=True, default='not_required', max_length=20),
        ),
    ]
