# Generated by Django 6.0.2 on 2026-10-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_bom_is_active_bom_status_bom_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='quarantine_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('quarantine', 'Quarantine'), ('available', 'Available'), ('rejected', 'Rejected'), ('hold', 'Hold')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_quarantine',
            field=models.BooleanField(default=False, help_text='Designates this warehouse as a quarantine isolation location'),
        ),
    ]
