# Generated by Django 6.0.2 on 2026-10-07 18:01

from django.db import migrations


def normalize_semi_finished_categories(apps, schema_editor):
    Item = apps.get_model("inventory", "Item")
    Item.objects.filter(category="semi_finished").update(category="intermediate")
    Item.objects.filter(erp_classification="semi_finished").update(erp_classification="intermediate")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_batch_parent_batch_qa_status'),
        ('inventory', '0022_batch_quarantine_released_at_batch_status_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_semi_finished_categories, migrations.RunPython.noop),
    ]
