# Generated by Django 6.0.2 on 2026-10-07 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_merge_20261007_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='costing_rule',
            field=models.CharField(choices=[('purchase_cost', 'Item purchase cost'), ('latest_po', 'Latest purchase price'), ('weighted_average', 'Weighted average'), ('standard', 'Standard cost')], default='purchase_cost', max_length=24),
        ),
        migrations.AddField(
            model_name='item',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_items', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='item',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='minimum_order_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='safety_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('general', 'General'), ('raw_material', 'Raw Material / Purchasing'), ('production', 'Production / Shop Floor'), ('finished_goods', 'Finished Goods'), ('virtual', 'Virtual')], default='general', max_length=24),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='raw_material',
            field=models.ForeignKey(limit_choices_to={'category__in': ['raw_material', 'packaging', 'intermediate', 'semi_finished']}, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('raw_material', 'Raw Material'), ('packaging', 'Packaging / Other Material'), ('intermediate', 'Intermediate (semi-finished)'), ('finished_good', 'Finished Good')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='erp_classification',
            field=models.CharField(blank=True, choices=[('raw_material', 'Raw Material'), ('packaging', 'Packaging / Other Material'), ('intermediate', 'Intermediate (semi-finished)'), ('finished_good', 'Finished Good'), ('out_of_scope', 'Out of Scope')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ItemUOMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=8, help_text='Quantity in target units for one source unit (e.g. 1 case = 12 each).', max_digits=20)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.unitofmeasure')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversions', to='inventory.item')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.unitofmeasure')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'from_unit', 'to_unit'), name='uniq_item_uom_conversion'), models.CheckConstraint(condition=models.Q(('factor__gt', 0)), name='item_uom_conversion_factor_positive')],
            },
        ),
    ]
