# Generated by Django 6.0.2 on 2026-10-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_item_costing_rule_item_default_warehouse_and_more'),
        ('production', '0020_convert_existing_recipes_to_boms'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_requests', to='production.productionplan'),
        ),
    ]
