# Generated by Django 6.0.4 on 2026-10-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_inventoryrequest_production_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('raw_material', 'Raw Material'), ('packaging', 'Packaging / Other Material'), ('intermediate', 'Semi-Finished'), ('finished_good', 'Finished Good')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='erp_classification',
            field=models.CharField(blank=True, choices=[('raw_material', 'Raw Material'), ('packaging', 'Packaging / Other Material'), ('intermediate', 'Semi-Finished'), ('finished_good', 'Finished Good'), ('out_of_scope', 'Out of Scope')], max_length=20, null=True),
        ),
    ]
