# Generated by Django 6.0.2 on 2026-04-23 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='erp_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('store', 'Store'), ('production', 'Production'), ('sales', 'Sales'), ('quality', 'Quality')], default='readonly', max_length=30),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
