# Generated by Django 6.0.2 on 2026-07-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickbooksentitylink',
            name='entity_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('item', 'Item'), ('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('report', 'Report')], max_length=50),
        ),
    ]
