# Generated by Django 6.0.2 on 2026-09-29 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_quickbooks_mirroring'),
        ('accounts', '0008_alter_company_id_alter_companysubscription_id_and_more'),
        ('quickbooks', '0002_alter_quickbooksentitylink_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickbooksentitylink',
            name='entity_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('item', 'Item'), ('invoice', 'Invoice'), ('bill', 'Bill'), ('payment', 'Payment'), ('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('bill_payment', 'Bill Payment'), ('journal_entry', 'Journal Entry'), ('report', 'Report')], max_length=50),
        ),
        migrations.CreateModel(
            name='QuickBooksAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickbooks_account_id', models.CharField(max_length=100)),
                ('quickbooks_account_name', models.CharField(blank=True, max_length=255)),
                ('quickbooks_account_type', models.CharField(blank=True, max_length=100)),
                ('auto_mapped', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_mapping', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'ordering': ['account__code'],
            },
        ),
    ]
