# Generated by Django 6.0.2 on 2026-09-30 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0003_quickbooks_mirroring'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookssyncrun',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
