# Generated by Django 5.2.15 on 2026-07-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_qualitycheck_parameter_qualitycheck_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycheck',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
