# Generated by Django 5.2.15 on 2026-07-29 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_batch_company_batch_created_at_batch_goods_receipt_and_more'),
        ('quality', '0003_alter_qualitycheck_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycheck',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='inventory.batch'),
        ),
    ]
