# Generated by Django 6.0.2 on 2026-10-06 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_batch_parent_batch_qa_status'),
        ('procurement', '0012_quickbooks_mirroring'),
        ('production', '0013_productionorder_notes_productionorder_order_number_and_more'),
        ('quality', '0004_qualitycheck_lot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycheck',
            name='accepted_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='certificate_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='procurement.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='inspection_type',
            field=models.CharField(choices=[('production', 'Production / Finished Goods'), ('incoming', 'Incoming Raw Material')], default='production', max_length=20),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='production.productionoutput'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='parameters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='quarantined_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='received_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='rejected_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='result_decision',
            field=models.CharField(blank=True, choices=[('', 'Not decided'), ('pass', 'Pass'), ('partial', 'Partial pass'), ('fail', 'Fail'), ('quarantine', 'Quarantine'), ('rework', 'Rework Required')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='rework_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='sample_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.productionorder'),
        ),
    ]
