# Generated by Django 6.0.2 on 2026-10-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_alter_qualitycheck_id_incomingqualitycheck'),
        ('quality', '0005_qualitycheck_accepted_quantity_and_more'),
    ]

    operations = [
    ]
