# Generated by Django 6.0.2 on 2026-02-24 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('line', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('idle', 'Idle'), ('maintenance', 'Maintenance'), ('breakdown', 'Breakdown')], default='running', max_length=20)),
                ('health', models.IntegerField(default=100)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('uptime', models.FloatField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('predictive', 'Predictive')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('assignee', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField()),
                ('estimated_duration', models.CharField(max_length=50)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipment')),
            ],
        ),
    ]
