# Generated by Django 6.0.2 on 2026-02-26 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancetask_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_maintenance_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], default='scheduled', max_length=20),
        ),
    ]
