# Generated by Django 6.0.2 on 2026-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancetask_initiated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
