# Generated by Django 6.0.2 on 2026-02-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenancetask_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='scheduled_date',
            field=models.DateTimeField(),
        ),
    ]
