# Generated by Django 6.0.2 on 2026-02-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_maintenancetask_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='assignee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='estimated_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
