# Generated by Django 6.0.2 on 2026-02-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_maintenancetask_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], default='requested', max_length=20),
        ),
    ]
