# Generated by Django 6.0.2 on 2026-02-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_maintenancetask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='technician_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed fee for the technician', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='technician_name',
            field=models.CharField(blank=True, help_text='Full name of assigned technician', max_length=200, null=True),
        ),
    ]
