# Generated by Django 6.0.2 on 2026-02-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_maintenancetask_technician_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost/amount for the maintenance job', max_digits=10, null=True),
        ),
    ]
