# Generated by Django 6.0.2 on 2026-02-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_maintenancetask_estimated_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetask',
            name='estimated_cost',
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='General maintenance cost or requested fee', max_digits=10),
        ),
    ]
