# Generated by Django 6.0.2 on 2026-09-24 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_company_id_alter_companysubscription_id_and_more'),
        ('inventory', '0020_alter_batch_id_alter_bom_id_alter_bomline_id_and_more'),
        ('procurement', '0010_bill_amount_paid_alter_bill_status_vendorpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('scheduled_date', models.DateField(db_index=True)),
                ('repeat', models.CharField(choices=[('none', 'Once'), ('weekly', 'Every week'), ('monthly', 'Every month')], default='none', max_length=10)),
                ('anchor_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('placed', 'Placed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('runs_count', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_purchases', to='inventory.item')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procurement.purchaseorder')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_purchases', to='procurement.vendor')),
            ],
            options={
                'ordering': ['scheduled_date', 'id'],
            },
        ),
    ]
