# Generated by Django 6.0.2 on 2026-10-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_purchaserequisition_purchaseorder_requisition_and_more'),
        ('procurement', '0012_quickbooks_mirroring'),
    ]

    operations = [
    ]
