# Generated by Django 6.0.2 on 2026-10-07 19:39

import django.db.models.deletion
from django.db import migrations, models


def backfill_purchase_units(apps, schema_editor):
    PurchaseOrderItem = apps.get_model("procurement", "PurchaseOrderItem")
    Item = apps.get_model("inventory", "Item")
    batch = []
    for line in PurchaseOrderItem.objects.filter(unit_of_measure__isnull=True).iterator():
        item = Item.objects.filter(pk=line.item_id).only("purchase_unit_id", "base_unit_id").first()
        if item:
            line.unit_of_measure_id = item.purchase_unit_id or item.base_unit_id
            if line.unit_of_measure_id:
                batch.append(line)
        if len(batch) >= 500:
            PurchaseOrderItem.objects.bulk_update(batch, ["unit_of_measure"])
            batch.clear()
    if batch:
        PurchaseOrderItem.objects.bulk_update(batch, ["unit_of_measure"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_item_costing_rule_item_default_warehouse_and_more'),
        ('procurement', '0013_merge_20261007_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.unitofmeasure'),
        ),
        migrations.RunPython(backfill_purchase_units, migrations.RunPython.noop),
    ]
