# Generated by Django 6.0.2 on 2026-09-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_company_id_alter_companysubscription_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('code_prefix', models.CharField(blank=True, help_text='e.g. 10 for Cash & Bank, 20 for Payables', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='System-defined standard account types cannot be deleted.')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique account code per company, e.g. 1010, 1020, 2010', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts cannot be selected in new transactions.')),
                ('is_reconciled', models.BooleanField(default=False, help_text='Flag indicating whether this account undergoes periodic reconciliation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.company')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent account for hierarchical chart of accounts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accounttype')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. FY 2026, 2026-2027', max_length=50)),
                ('start_date', models.DateField(help_text='First day of the fiscal year')),
                ('end_date', models.DateField(help_text='Last day of the fiscal year')),
                ('is_closed', models.BooleanField(default=False, help_text='Indicates whether the fiscal year is closed for journal postings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Tenant company that owns this fiscal year.', on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='accounts.company')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(default='USD', max_length=10)),
                ('lock_date', models.DateField(blank=True, help_text='Transactions on or prior to this date cannot be created, modified or deleted.', null=True)),
                ('allow_direct_posting_to_parent_accounts', models.BooleanField(default=False, help_text='If false, entries can only be posted to leaf (non-parent) accounts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_settings', to='accounts.company')),
                ('retained_earnings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('current_fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.fiscalyear')),
            ],
            options={
                'verbose_name_plural': 'Accounting Settings',
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveSmallIntegerField(help_text='Sequential period number within the fiscal year (1-12/13)')),
                ('name', models.CharField(help_text='e.g. Jan 2026, Q1 2026', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('locked', 'Locked')], default='open', help_text='Open = accepts postings, Locked = temporary freeze, Closed = finalized.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_periods', to='accounts.company')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear')),
            ],
            options={
                'ordering': ['fiscal_year__start_date', 'period_number'],
                'unique_together': {('company', 'fiscal_year', 'name'), ('company', 'fiscal_year', 'period_number')},
            },
        ),
    ]
