# Generated by Django 6.0.2 on 2026-09-23 19:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('accounts', '0009_alter_company_id_alter_companysubscription_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(db_index=True, help_text='Unique sequence number e.g. JE-2026-00001', max_length=64)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, help_text='The effective accounting date of the transaction.')),
                ('reference', models.CharField(blank=True, default='', help_text='Source document or reference number (e.g. INV-1002, PO-5001)', max_length=128)),
                ('description', models.TextField(blank=True, default='', help_text='Transaction narration or business purpose.')),
                ('source_module', models.CharField(default='manual', help_text='Originating ERP module: manual, sales, procurement, inventory, production, etc.', max_length=50)),
                ('source_id', models.PositiveIntegerField(blank=True, help_text='PK of the source document in the originating module.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_period', models.ForeignKey(blank=True, help_text='Accounting period this transaction falls within.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='accounting.accountingperiod')),
                ('company', models.ForeignKey(help_text='Tenant company that owns this journal entry.', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, help_text='Points to the original journal entry if this is a reversal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveSmallIntegerField(default=1)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('description', models.CharField(blank=True, default='', help_text='Line item memo or specific reference.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='accounts.company')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['line_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'status', 'transaction_date'], name='accounting__company_2d8add_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'entry_number'], name='accounting__company_40375a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('company', 'entry_number')},
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['company', 'account'], name='accounting__company_1d2097_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journal_entry', 'line_number'], name='accounting__journal_9d000e_idx'),
        ),
    ]
