# Generated by Django 6.0.2 on 2026-09-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_journalentryline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='inventory_accounting_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable automated/subledger inventory accounting.'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='inventory_adjustment_account',
            field=models.ForeignKey(blank=True, help_text='Offset account for cycle count and manual inventory adjustments (e.g. 5090 Inventory Adjustments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='inventory_clearing_account',
            field=models.ForeignKey(blank=True, help_text='Clearing/offset account for vendor receipts (e.g. 2010 AP or 2020 GRNI)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='inventory_cogs_account',
            field=models.ForeignKey(blank=True, help_text='Offset account for inventory issues/consumption (e.g. 5010 Direct Materials Consumed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='inventory_costing_method',
            field=models.CharField(choices=[('fifo', 'FIFO (First In, First Out)'), ('standard', 'Standard Cost'), ('average', 'Weighted Average')], default='fifo', help_text='Configured inventory costing valuation policy.', max_length=20),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='inventory_finished_goods_account',
            field=models.ForeignKey(blank=True, help_text='Default leaf asset account for Finished Goods inventory (e.g. 1230)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='inventory_raw_material_account',
            field=models.ForeignKey(blank=True, help_text='Default leaf asset account for Raw Materials inventory (e.g. 1210)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='inventory_write_off_account',
            field=models.ForeignKey(blank=True, help_text='Expense account for damaged/expired inventory write-offs (e.g. 6520 Inventory Write-off)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
    ]
