# Generated by Django 6.0.2 on 2026-09-24 18:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountingsettings_inventory_accounting_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='labor_accounting_enabled',
            field=models.BooleanField(default=False, help_text='Capitalize direct labor into WIP costs.'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='labor_rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard direct labor cost per finished unit produced.', max_digits=10),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='manufacturing_accounting_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable automated/subledger manufacturing accounting.'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='manufacturing_labor_account',
            field=models.ForeignKey(blank=True, help_text='Clearing or expense account for direct labor (e.g. 2100 Accrued Payroll or 5100 Direct Labor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='manufacturing_overhead_account',
            field=models.ForeignKey(blank=True, help_text='Clearing or applied account for factory overhead (e.g. 5040 Overhead Applied or 5200 Factory Utilities)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='manufacturing_scrap_account',
            field=models.ForeignKey(blank=True, help_text='Expense account for production scrap and defectives (e.g. 5080 Scrap Loss or 6520 Inventory Loss)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='manufacturing_variance_account',
            field=models.ForeignKey(blank=True, help_text='Account for manufacturing cost variances (e.g. 5090 Manufacturing Variance)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='manufacturing_wip_account',
            field=models.ForeignKey(blank=True, help_text='Asset account for Work-In-Progress (e.g. 1220 WIP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='overhead_accounting_enabled',
            field=models.BooleanField(default=False, help_text='Apply manufacturing overhead into WIP costs.'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='overhead_rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard applied manufacturing overhead per finished unit produced.', max_digits=10),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='scrap_accounting_enabled',
            field=models.BooleanField(default=True, help_text='Account for production scrap and rejected batches.'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='variance_accounting_enabled',
            field=models.BooleanField(default=True, help_text='Calculate and record manufacturing variances upon order completion.'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='wip_accounting_enabled',
            field=models.BooleanField(default=True, help_text='Track Work-In-Process (WIP) asset balance during active production.'),
        ),
    ]
