# Generated by Django 6.0.2 on 2026-09-24 18:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accountingsettings_labor_accounting_enabled_and_more'),
        ('accounts', '0009_alter_company_id_alter_companysubscription_id_and_more'),
        ('procurement', '0010_bill_amount_paid_alter_bill_status_vendorpayment'),
        ('workforce', '0003_department_company_employee_company_shift_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='expenses_accounting_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable automated/subledger expenses accounting.'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='expenses_default_bank_account',
            field=models.ForeignKey(blank=True, help_text='Default leaf bank account for bank expenses (e.g. 1010 Operating Bank Account)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='expenses_default_cash_account',
            field=models.ForeignKey(blank=True, help_text='Default leaf cash account for cash expenses (e.g. 1030 Petty Cash)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='expenses_default_employee_payable_account',
            field=models.ForeignKey(blank=True, help_text='Default leaf payable account for employee reimbursements (e.g. 2100 Accrued Payroll/Reimbursements)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='expenses_default_payable_account',
            field=models.ForeignKey(blank=True, help_text='Default leaf AP account for vendor expenses (e.g. 2010 Accounts Payable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='expenses_default_tax_account',
            field=models.ForeignKey(blank=True, help_text='Default leaf input tax recoverable account for expense taxes (e.g. 1310 Input Tax Recoverable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='expenses_require_approval',
            field=models.BooleanField(default=True, help_text='Require approval before expenses can be posted to the General Ledger.'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(db_index=True, max_length=64)),
                ('expense_type', models.CharField(choices=[('employee', 'Employee Expense'), ('vendor', 'Vendor Expense')], default='employee', max_length=20)),
                ('vendor_name_raw', models.CharField(blank=True, default='', help_text='Unregistered vendor name memo', max_length=255)),
                ('title', models.CharField(help_text='Summary title of the expense', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('accounting_date', models.DateField(blank=True, help_text='Accounting/posting date for GL recognition', null=True)),
                ('amount_before_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_source', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer / Card'), ('payable', 'Payable / Reimbursement')], default='payable', max_length=20)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('accounting_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('ready', 'Ready for GL'), ('posted', 'Posted to GL'), ('reversed', 'Reversed'), ('failed', 'Failed')], default='not_ready', max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('receipt_name', models.CharField(blank=True, default='', max_length=255)),
                ('receipt_size', models.IntegerField(blank=True, null=True)),
                ('receipt_content_type', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Tenant company context.', on_delete=django.db.models.deletion.CASCADE, related_name='accounting_expenses', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Employee claiming reimbursement (for employee expenses)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='workforce.employee')),
                ('expense_account', models.ForeignKey(blank=True, help_text='Specific leaf expense account overriding category default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Posted double-entry general ledger journal entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.journalentry')),
                ('payment_account', models.ForeignKey(blank=True, help_text='Specific leaf cash, bank, or payable account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_expenses', to=settings.AUTH_USER_MODEL)),
                ('reversal_journal_entry', models.ForeignKey(blank=True, help_text='Offsetting reversal journal entry if reversed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_expenses', to='accounting.journalentry')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_expenses', to=settings.AUTH_USER_MODEL)),
                ('tax_account', models.ForeignKey(blank=True, help_text='Specific leaf input tax recoverable account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('vendor', models.ForeignKey(blank=True, help_text='Registered supplier (for vendor expenses)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action code, e.g. created, receipt_attached, submitted, approved, rejected, previewed, posted, reversed, cancelled', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured event telemetry / state diff')),
                ('notes', models.TextField(blank=True, default='', help_text='User comments, approval remarks, or rejection reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User executing the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(help_text='Parent expense record.', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounting.expense')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique category identifier, e.g. TRAVEL, MEALS, SOFTWARE', max_length=50)),
                ('name', models.CharField(help_text='Descriptive category name', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Tenant company owning this expense category.', on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='accounts.company')),
                ('expense_account', models.ForeignKey(blank=True, help_text='Default leaf expense account mapped to this category (e.g. 6020 Sales/Travel, 6040 Software)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorized_expenses', to='accounting.account')),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(help_text='Configured expense category defining default GL account mapping', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.expensecategory'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'expense_number'], name='accounting__company_2b3f91_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'approval_status'], name='accounting__company_3bc695_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'accounting_status'], name='accounting__company_4e47b9_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'expense_date'], name='accounting__company_12e032_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('company', 'expense_number')},
        ),
    ]
