# Generated by Django 6.0.2 on 2026-09-26 13:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_accountingsettings_expenses_accounting_enabled_and_more'),
        ('accounts', '0009_alter_company_id_alter_companysubscription_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='opening_balance_equity_account',
            field=models.ForeignKey(blank=True, help_text='Leaf equity account for opening balance offset (e.g. 3010 Common Stock / Owner Capital)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='is_reconciled',
            field=models.BooleanField(default=False, help_text='Whether this line item has been matched and cleared in bank reconciliation.'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='Descriptive title, e.g. Operating Checking, Payroll Account', max_length=150)),
                ('bank_name', models.CharField(help_text='Institution name, e.g. JPMorgan Chase, Silicon Valley Bank', max_length=150)),
                ('account_number', models.CharField(help_text='Account number (masked in API/UI)', max_length=50)),
                ('routing_number', models.CharField(blank=True, default='', help_text='ABA routing / sort code', max_length=50)),
                ('swift_bic', models.CharField(blank=True, default='', help_text='SWIFT / BIC code for wire transfers', max_length=50)),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('money_market', 'Money Market'), ('credit_card', 'Credit Card'), ('cash', 'Petty Cash / Vault')], default='checking', max_length=30)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('opening_balance_posted', models.BooleanField(default=False)),
                ('reconciled_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('last_reconciliation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Tenant company owning this bank account.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.company')),
                ('gl_account', models.ForeignKey(help_text='Linked leaf Chart of Accounts asset or liability account (e.g. 1010, 1020, 1030)', on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.account')),
                ('opening_balance_journal_entry', models.ForeignKey(blank=True, help_text='General Ledger journal entry for the opening balance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['bank_name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_number', models.CharField(db_index=True, max_length=64)),
                ('statement_date', models.DateField(help_text='Cut-off date of the external bank statement')),
                ('statement_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ending statement balance', max_digits=18)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Previous reconciled starting balance', max_digits=18)),
                ('reconciled_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Target reconciled balance after reconciliation', max_digits=18)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Difference between statement and reconciled items', max_digits=18)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('reopened', 'Reopened')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(help_text='Reconciled bank account.', on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounting.bankaccount')),
                ('company', models.ForeignKey(help_text='Tenant company owning this reconciliation cycle.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliations', to='accounts.company')),
                ('reconciled_by', models.ForeignKey(blank=True, help_text='User executing the reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. account_created, opening_balance_posted, deposit_recorded, withdrawal_recorded, transfer_recorded, statement_imported, reconciliation_completed, reconciliation_reopened', max_length=60)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounting.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_audit_logs', to='accounts.company')),
                ('reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounting.bankreconciliation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='reconciliation',
            field=models.ForeignKey(blank=True, help_text='Bank reconciliation cycle in which this line was cleared.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_journal_lines', to='accounting.bankreconciliation'),
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Absolute transaction amount', max_digits=18)),
                ('direction', models.CharField(choices=[('inflow', 'Inflow / Deposit / DR'), ('outflow', 'Outflow / Withdrawal / CR')], default='inflow', max_length=10)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Bank Transfer'), ('customer_receipt', 'Customer Receipt'), ('vendor_payment', 'Vendor Payment'), ('expense_payment', 'Expense Payment'), ('fee', 'Bank Fee / Charge'), ('interest', 'Interest Income'), ('statement_line', 'Imported Statement Line'), ('opening_balance', 'Opening Balance'), ('other', 'Other Transaction')], default='deposit', max_length=30)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('import', 'Statement Import'), ('erp', 'ERP Subledger Posting')], default='manual', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', help_text='Cheque #, reference or memo', max_length=100)),
                ('counterparty', models.CharField(blank=True, default='', help_text='Payee or payer name', max_length=150)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', help_text='Unique statement transaction identifier for idempotency', max_length=100)),
                ('matching_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('suggested', 'Suggested Match'), ('matched', 'Matched')], default='unmatched', max_length=20)),
                ('reconciliation_status', models.CharField(choices=[('unreconciled', 'Unreconciled'), ('reconciled', 'Reconciled')], default='unreconciled', max_length=20)),
                ('source_document_ref', models.CharField(blank=True, default='', help_text='Traceability to AR/AP/Expense document, e.g. REC-001, PAY-002, EXP-003', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_transactions', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Linked posted double-entry journal entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='accounting.journalentry')),
                ('journal_entry_line', models.ForeignKey(blank=True, help_text='Specific GL journal line for this bank account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='accounting.journalentryline')),
                ('reconciliation', models.ForeignKey(blank=True, help_text='Reconciliation cycle in which this transaction was cleared', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.bankreconciliation')),
                ('transfer_counterpart', models.OneToOneField(blank=True, help_text='Linked matching transaction in destination/source bank account for internal transfers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterpart_transaction', to='accounting.banktransaction')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['company', 'is_active'], name='accounting__company_9b20b0_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['company', 'gl_account'], name='accounting__company_25a89f_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['company', 'bank_account'], name='accounting__company_b36b40_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['company', 'statement_date'], name='accounting__company_f118a6_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'bank_account', 'reconciliation_status'], name='accounting__company_693b93_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'transaction_date'], name='accounting__company_b4be43_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account', 'external_id'], name='accounting__bank_ac_57a493_idx'),
        ),
    ]
