# Generated by Django 6.0.2 on 2026-09-26 13:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_accountingsettings_opening_balance_equity_account_and_more'),
        ('accounts', '0009_alter_company_id_alter_companysubscription_id_and_more'),
        ('procurement', '0010_bill_amount_paid_alter_bill_status_vendorpayment'),
        ('sales', '0012_alter_customer_address_alter_customer_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, db_index=True, help_text='Sequential human-readable identifier (e.g. REC-2026-00001 or PAY-2026-00001)', max_length=50)),
                ('payment_type', models.CharField(choices=[('customer_receipt', 'Customer Receipt'), ('vendor_payment', 'Vendor Payment')], default='customer_receipt', max_length=30)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payment transaction amount', max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_source_type', models.CharField(choices=[('bank', 'Bank Account'), ('cash', 'Cash Account')], default='bank', max_length=20)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('upi', 'UPI / Electronic'), ('other', 'Other')], default='bank_transfer', max_length=30)),
                ('reference', models.CharField(blank=True, default='', help_text='Cheque #, UTR, transaction ref or memo', max_length=100)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', help_text='External unique ID for idempotency', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('allocation_status', models.CharField(choices=[('unallocated', 'Unallocated'), ('partially_allocated', 'Partially Allocated'), ('fully_allocated', 'Fully Allocated')], default='unallocated', max_length=25)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.bankaccount')),
                ('bank_transaction', models.ForeignKey(blank=True, help_text='Linked BankTransaction in Cash & Bank subledger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_payments', to='accounting.banktransaction')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_payments', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_payments', to='sales.customer')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Linked GL double-entry journal entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_payments', to='accounting.journalentry')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_accounting_payments', to='accounting.journalentry')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_payments', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('allocation_date', models.DateField(default=django.utils.timezone.now)),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Amount applied to the specific document', max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reversed', 'Reversed')], default='active', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_allocations', to='procurement.bill')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allocations', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_allocations', to='sales.invoice')),
                ('legacy_customer_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_allocations', to='sales.customerpayment')),
                ('legacy_vendor_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_allocations', to='procurement.vendorpayment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. payment_created, payment_posted, allocation_created, allocation_unallocated, payment_cancelled, payment_reversed', max_length=60)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_audit_logs', to='accounts.company')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounting.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'payment_type', 'status'], name='accounting__company_43d34e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'allocation_status'], name='accounting__company_236864_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'external_reference'], name='accounting__company_f1f86c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['company', 'status'], name='accounting__company_9172a6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment', 'status'], name='accounting__payment_a50d58_idx'),
        ),
    ]
