# Generated by Django 6.0.2 on 2026-09-26 13:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_payment_paymentallocation_paymentauditlog_and_more'),
        ('accounts', '0009_alter_company_id_alter_companysubscription_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_purchase_tax_account',
            field=models.ForeignKey(blank=True, help_text='Default leaf input tax recoverable account (e.g. 1310 Input Tax Recoverable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_sales_tax_account',
            field=models.ForeignKey(blank=True, help_text='Default leaf sales tax payable account (e.g. 2200 Sales Tax Payable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique tax code, e.g. STD-18, ZERO, EXEMPT, VAT-20', max_length=30)),
                ('name', models.CharField(help_text='Human-readable description, e.g. Standard Sales Tax 18%', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Tax rate percentage (e.g. 18.0000 for 18%)', max_digits=7)),
                ('tax_type', models.CharField(choices=[('sales', 'Output Tax (Sales)'), ('purchase', 'Input Tax (Purchase)'), ('both', 'Both (Sales & Purchase)'), ('other', 'Other / Special Tax')], default='both', max_length=20)),
                ('calculation_mode', models.CharField(choices=[('exclusive', 'Tax Exclusive'), ('inclusive', 'Tax Inclusive')], default='exclusive', max_length=20)),
                ('is_recoverable', models.BooleanField(default=True, help_text='Whether input tax under this code can be claimed/recovered as an asset tax credit')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Tenant company that owns this tax code.', on_delete=django.db.models.deletion.CASCADE, related_name='tax_codes', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tax_account', models.ForeignKey(help_text='Active leaf account mapped for posting this tax (e.g. 2200 Sales Tax Payable or 1310 Input Tax Recoverable)', on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes', to='accounting.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(max_length=60, unique=True)),
                ('adjustment_direction', models.CharField(choices=[('increase_liability', 'Increase Tax Liability (Output Tax)'), ('decrease_liability', 'Decrease Tax Liability (Output Tax)'), ('increase_credit', 'Increase Input Tax Credit'), ('decrease_credit', 'Decrease Input Tax Credit')], default='increase_liability', max_length=30)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Adjustment amount (positive)', max_digits=18)),
                ('adjustment_date', models.DateField()),
                ('reason', models.TextField(help_text='Mandatory business reason / justification')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_adjustments', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_adjustment_entries', to='accounting.journalentry')),
                ('offset_account', models.ForeignKey(help_text='Balancing offset account (e.g. Tax Expense, General Expense, Revenue, or Retained Earnings)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journalentry')),
                ('tax_account', models.ForeignKey(help_text='The tax liability or asset account being adjusted', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='accounting.taxcode')),
            ],
            options={
                'ordering': ['-adjustment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_tax_code',
            field=models.ForeignKey(blank=True, help_text='Default active tax code for sales and purchase transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.taxcode'),
        ),
        migrations.CreateModel(
            name='TaxTransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_module', models.CharField(choices=[('sales', 'Sales Invoice'), ('purchases', 'Purchase Bill'), ('expenses', 'Expense'), ('tax_adjustment', 'Tax Adjustment'), ('manual', 'Manual Journal / Direct')], max_length=30)),
                ('source_id', models.CharField(blank=True, default='', help_text='Primary key of source record', max_length=100)),
                ('source_reference', models.CharField(blank=True, default='', help_text='Human identifier e.g. INV-2026-0001', max_length=100)),
                ('source_line_id', models.CharField(blank=True, default='', max_length=100)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('calculation_mode', models.CharField(default='exclusive', max_length=20)),
                ('transaction_date', models.DateField()),
                ('is_posted', models.BooleanField(default=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reference', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_transaction_lines', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_lines', to='accounting.journalentry')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journalentry')),
                ('tax_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_transaction_lines', to='accounting.account')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='accounting.taxcode')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. tax_code_created, tax_code_updated, tax_code_deactivated, tax_adjustment_posted, tax_reversed', max_length=60)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_audit_logs', to='accounts.company')),
                ('tax_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.taxadjustment')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.taxcode')),
                ('tax_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.taxtransactionline')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='taxadjustment',
            name='original_tax_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='accounting.taxtransactionline'),
        ),
        migrations.AddIndex(
            model_name='taxtransactionline',
            index=models.Index(fields=['company', 'source_module', 'source_id'], name='accounting__company_c70c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransactionline',
            index=models.Index(fields=['company', 'transaction_date'], name='accounting__company_099b81_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransactionline',
            index=models.Index(fields=['company', 'is_reversed'], name='accounting__company_0e7e2e_idx'),
        ),
    ]
