# Generated by Django 6.0.2 on 2026-09-24 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_accountingperiod_closed_at_and_more'),
        ('accounts', '0008_alter_company_id_alter_companysubscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_post_enabled',
            field=models.BooleanField(default=True, help_text='Automatically post goods receipts, vendor bills, production, shipments, sales invoices and customer payments to the General Ledger.'),
        ),
        migrations.CreateModel(
            name='AutoPostingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=40)),
                ('source_id', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='acct_autopost_status_idx')],
            },
        ),
    ]
