# Generated by Django 6.0.2 on 2026-09-30 14:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_accountingperiod_closed_at_and_more'),
        ('accounts', '0009_alter_company_id_alter_companysubscription_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created Draft'), ('UPDATED', 'Updated Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTED', 'Posted to Ledger'), ('REVERSED', 'Reversed'), ('EMERGENCY_OVERRIDE', 'Emergency Override Posting'), ('ATTACHMENT_ADDED', 'Attachment Added'), ('ATTACHMENT_REMOVED', 'Attachment Removed'), ('DELETED', 'Draft Deleted')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ApprovalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(db_index=True, help_text='Document type: journal_entry, expense, bill, payment', max_length=50)),
                ('document_id', models.CharField(db_index=True, max_length=64)),
                ('document_number', models.CharField(db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EMERGENCY_OVERRIDE', 'Emergency Override Posting'), ('REVERTED_DRAFT', 'Reverted to Draft')], db_index=True, max_length=30)),
                ('actor_role', models.CharField(blank=True, default='', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('emergency_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('routing_tier', models.CharField(blank=True, default='standard', max_length=50)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_approval_actions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_audit_logs', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('all', 'All Modules'), ('journal_entry', 'Journal Entries'), ('expense', 'Expenses'), ('bill', 'Supplier Bills'), ('payment', 'Payments')], default='all', help_text='Module or transaction category governed by this threshold.', max_length=50)),
                ('standard_threshold', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Transactions exceeding this value strictly require manager approval.', max_digits=14)),
                ('high_value_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Transactions exceeding this value require executive / admin approval.', max_digits=14)),
                ('approver_role', models.CharField(default='finance_manager', help_text='Minimum accounting role required to approve standard-tier transactions.', max_length=50)),
                ('high_value_approver_role', models.CharField(default='accounting_admin', help_text='Role required to approve high-value transactions.', max_length=50)),
                ('enforce_segregation_of_duties', models.BooleanField(default=True, help_text='Enforces 4-eyes principle (requester / creator cannot approve their own item).')),
                ('allow_emergency_override', models.BooleanField(default=True, help_text='Permits executive emergency posting with documented reason and enhanced audit logging.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this approval policy is currently enforced.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Tenant company context.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_thresholds', to='accounts.company')),
            ],
            options={
                'ordering': ['module'],
                'unique_together': {('company', 'module')},
            },
        ),
    ]
