# Generated by Django 6.0.2 on 2026-09-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='auto_bill_on_receipt',
            field=models.BooleanField(default=True, help_text='Create the vendor bill from the purchase order automatically when its goods are received.'),
        ),
    ]
