# Generated by Django 6.0.2 on 2026-09-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_bill_on_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='quickbooks_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='quickbooks_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='quickbooks_sync_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
