# Generated by Django 6.0.2 on 2026-10-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_journalentryauditlog_action_approvalauditlog_and_more'),
        ('accounting', '0013_quickbooks_mirroring'),
    ]

    operations = [
    ]
