# Generated by Django 6.0.2 on 2026-02-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_customer_contact_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='departure_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_arrival',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('loading', 'Loading'), ('in-transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed')], default='preparing', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
