# Generated by Django 6.0.2 on 2026-02-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_shipment_departure_time_shipment_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='shipped_quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
