# Generated by Django 5.2.15 on 2026-07-29 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_company_id_alter_companysubscription_id_and_more'),
        ('sales', '0008_alter_customer_id_alter_customerpayment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('email', 'Email inbox')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='InboundOrderEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_body', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, help_text='0–1 extraction confidence', null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('parsed', 'Parsed'), ('needs_attention', 'Needs attention'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='sales.salesorder')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
