# Generated by Django 5.2.15 on 2026-07-29 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_batch_company_batch_created_at_batch_goods_receipt_and_more'),
        ('sales', '0009_salesorder_source_alter_salesorder_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipped_on', to='inventory.batch')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_lots', to='sales.shipment')),
            ],
        ),
    ]
