# Generated by Django 6.0.2 on 2026-10-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_customer_address_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_order_reference',
            field=models.CharField(blank=True, default='', help_text='Customer PO / external order reference', max_length=100),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='required_delivery_date',
            field=models.DateField(blank=True, help_text='Customer required delivery date', null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('email', 'Email inbox'), ('phone', 'Phone order'), ('other', 'Other external source')], default='manual', max_length=20),
        ),
    ]
