# Generated by Django 6.0.2 on 2026-10-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_salesorder_customer_order_reference_and_more'),
        ('sales', '0014_invoiceline_sales_order_item'),
    ]

    operations = [
    ]
