# Generated by Django 6.0.2 on 2026-10-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='custom_specifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
    ]
